fname=input("Enter the filename:")
fptr=open(fname,"r")
data1=fptr.read()
print(data1)
print("===========================================")
fname=input("Enter a filename:")
fptr=open(fname,"r")
data2=fptr.readline()
print(data2)
print("==============================================")
fname=input("Enter a filename:")
fptr=open(fname,"r")
data3=fptr.readlines()
print(data3)